version: '3.1'
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: ifood-test-db
    environment:
      MYSQL_DATABASE: ifood-test-db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3306:3306'
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: ifood-test-backend:latest
    container_name: ifood-test-backend
    restart: unless-stopped
    ports:
      - 3000:3000
    command: npm run start:dev
